//
// CouponTransactionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CouponTransactionResponse: JSONEncodable {
    public enum ModelType: String { 
        case charge = "CHARGE"
        case refund = "REFUND"
        case increaseBalance = "INCREASE_BALANCE"
        case decreaseBalance = "DECREASE_BALANCE"
        case expireBalance = "EXPIRE_BALANCE"
        case reciprocity = "RECIPROCITY"
        case claim = "CLAIM"
    }
    /** unique */
    public var id: String?
    public var created: Date?
    public var amount: Int32?
    public var type: ModelType?
    public var description: String?
    public var user: CouponUserResponse?
    public var coupon: CouponResponse?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["amount"] = self.amount?.encodeToJSON()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["description"] = self.description
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["coupon"] = self.coupon?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
