//
// CouponUserTransactionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CouponUserTransactionRequest: JSONEncodable {
    public var amount: Int32?
    public var reciprocate: Bool?
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["amount"] = self.amount?.encodeToJSON()
        nillableDictionary["reciprocate"] = self.reciprocate
        nillableDictionary["description"] = self.description
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
