//
// CouponUserResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** CouponUser object returned as a response */
open class CouponUserResponse: JSONEncodable {
    /** unique */
    public var id: String?
    public var enabled: Bool?
    public var created: Date?
    public var name: String?
    public var email: String?
    public var externalId: String?
    public var role: String?
    public var tags: [String]?
    public var balance: Int32?
    public var description: String?
    public var couponCount: Int32?
    public var lastClaim: Date?
    public var lastTransaction: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["email"] = self.email
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["role"] = self.role
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["balance"] = self.balance?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["coupon_count"] = self.couponCount?.encodeToJSON()
        nillableDictionary["last_claim"] = self.lastClaim?.encodeToJSON()
        nillableDictionary["last_transaction"] = self.lastTransaction?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
