//
// CouponTypeIssueRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CouponTypeIssueRequest: JSONEncodable {
    public var quantity: Int32?
    public var code: String?
    public var value: Int32?
    public var fromUserId: String?
    public var toUserId: String?
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["quantity"] = self.quantity?.encodeToJSON()
        nillableDictionary["code"] = self.code
        nillableDictionary["value"] = self.value?.encodeToJSON()
        nillableDictionary["from_user_id"] = self.fromUserId
        nillableDictionary["to_user_id"] = self.toUserId
        nillableDictionary["description"] = self.description
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
