//
// CouponTypeUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CouponTypeUpdateRequest: JSONEncodable {
    public var name: String?
    public var tags: [String]?
    public var description: String?
    public var expiry: Date?
    public var value: Int32?
    public var reciprocalValue: Int32?
    public var fences: Geojson?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["expiry"] = self.expiry?.encodeToJSON()
        nillableDictionary["value"] = self.value?.encodeToJSON()
        nillableDictionary["reciprocal_value"] = self.reciprocalValue?.encodeToJSON()
        nillableDictionary["fences"] = self.fences?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
