//
// CouponUserClaimRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CouponUserClaimRequest: JSONEncodable {
    /** latitude float number */
    public var lat: Float?
    /** longitude float number */
    public var lng: Float?
    public var description: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["lat"] = self.lat
        nillableDictionary["lng"] = self.lng
        nillableDictionary["description"] = self.description
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
