//
// CouponTypeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CouponTypeResponse: JSONEncodable {
    public enum CodeType: String { 
        case random = "RANDOM"
        case sequential = "SEQUENTIAL"
    }
    public enum Applicability: String { 
        case any = "ANY"
        case newUserOnly = "NEW_USER_ONLY"
    }
    /** unique */
    public var id: String?
    public var created: Date?
    public var cancelled: Date?
    public var expiry: Date?
    public var name: String?
    public var description: String?
    public var tags: [String]?
    public var value: Int32?
    public var reciprocalValue: Int32?
    /** Valid values are in settings */
    public var fromRole: String?
    /** Valid values are in settings */
    public var toRole: String?
    public var codeType: CodeType?
    public var codePrefix: String?
    public var claimLimit: Int32?
    public var issuedCount: Int32?
    public var applicability: Applicability?
    public var fences: Geojson?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["cancelled"] = self.cancelled?.encodeToJSON()
        nillableDictionary["expiry"] = self.expiry?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["value"] = self.value?.encodeToJSON()
        nillableDictionary["reciprocal_value"] = self.reciprocalValue?.encodeToJSON()
        nillableDictionary["from_role"] = self.fromRole
        nillableDictionary["to_role"] = self.toRole
        nillableDictionary["code_type"] = self.codeType?.rawValue
        nillableDictionary["code_prefix"] = self.codePrefix
        nillableDictionary["claim_limit"] = self.claimLimit?.encodeToJSON()
        nillableDictionary["issued_count"] = self.issuedCount?.encodeToJSON()
        nillableDictionary["applicability"] = self.applicability?.rawValue
        nillableDictionary["fences"] = self.fences?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
