//
// InlineResponse400.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse400: JSONEncodable {
    public enum Code: String { 
        case badValue = "BAD_VALUE"
        case validationError = "VALIDATION_ERROR"
        case applicationError = "APPLICATION_ERROR"
    }
    public var message: String?
    public var code: Code?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["message"] = self.message
        nillableDictionary["code"] = self.code?.rawValue
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
