//
// MetaList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The \&quot;meta\&quot; properties provide additional details about the lists and objects */
open class MetaList: JSONEncodable {
    public var object: String?
    public var count: Int32?
    public var totalCount: Int32?
    public var hasMore: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["object"] = self.object
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["total_count"] = self.totalCount?.encodeToJSON()
        nillableDictionary["has_more"] = self.hasMore
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
